---
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
platforms:
  - name: mail-receiver-srv
    image: centos:7
  - name: mail-relay-srv
    image: centos:7
  - name: mail-sender-srv
    image: centos:7

provisioner:
  name: ansible
verifier:
  name: ansible
